apiVersion: v2
appVersion: 1.16.1
dependencies:
- name: rethinkdb
  repository: ""
  version: 0.4.0
- name: enzi
  repository: ""
  version: 0.3.0
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ~10.3.15
description: A Helm chart for installing MSR on Kubernetes
name: msr
type: application
version: 0.1.1
