{{/*
  Yes, the auth signing cert is a root CA. This matches the behavior of MSR
  Classic. The trouble is that Garant expects a key in JWKS format, which
  embeds the certificate and private key into the same file, but cert-manager
  (and MSR Classic) only support emitting keys in a PEM file separately from
  the certificate PEM file. With no way to configure Garant with the
  certificate, it cannot embed the cert chain into the signed auth tokens.
  And with no cert chain, services cannot verify the auth tokens against the
  CA unless the signing certificate _is_ the CA. So here we are.
  TODO(12factor)(ENGDTR-2287): stop signing tokens with the CA cert.
*/}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-auth-signing-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-auth-signing-cert
  duration: 87600h # 10 years
  renewBefore: 24h
  commonName: "MSR Auth Token Signing CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
