
ansible:
  playbook:
    contents:
      - name: Install MCR on all targets
        hosts: all
        become: yes
        roles:
          - mirantis.mcr.common

      - name: Init swarm and add first manager
        hosts: manager0
        roles:
          - mirantis.mcr.leader

      - name: Add additional swarm managers
        hosts: managers:!manager0
        roles:
          - mirantis.mcr.manager

      - name: Add swarm workers
        hosts: workers:msrs
        roles:
          - mirantis.mcr.worker
