
# chaos_litmuschaos :: metta.plugin.workload:
chaos_litmuschaos:
    plugin_type: workload
    plugin_id: metta_litmuschaos_run

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    version: 1.13.3

    experiments:
    - charts/generic/experiments.yaml
    - charts/kube-aws/experiments.yaml

    application:
    - deploy/myapp
