# use these for metta_mirantis presets
#
# This preset list sets the components for the testing cluster which is used
# by all upgrade environments.  The different environments keep the same
# confguration primarily, and differ only in presets.  This means that they
# share assets (terraform/ansible/launchpad) and are effectively declarative
# for their state and can be used indepentently.
#
# Each environment contains overrides for the release preset, so we leave that
# out.
#
# We keep presets which really should not change across environments here only
# so that no accidental platform, variation or cluster change happens across
# environments, which would completely destroy the cluster when terraform
# sees a big changes.
#
presets:
    # This will tell metta to include metta/config/variation/ltc
    variation: tal
    # this will tell metta to include metta/config/release/patch/202106
    release: patch/202106
    # This will tell metta to include metta/config/cluster/poc
    cluster: poc
    # This will tell metta to include metta/config/platform/public/ubuntu/20.04
    platform: public/ubuntu/20.04
