# Environment: BEFORE mirantis config
presets:

    # release preset is set per environment, so we ignore it heres
    # this will tell metta to include metta_mirantis/config/release/release/2021Q1
    release: release/2021Q1
