# what does launchpad call this cluster (has to match `metadata.name` in the yml)
cluster_name: "existing"
config_file: "{paths:project}/launchpad/{cluster_name}.yaml"

backend:
    plugin_id: existing
    # this tells the launchpad provisioner what output from the backend plugin to
    # use to get its yml to pass to the plugin
    output: mke_yaml

    config:
        # this config is passed as provisioner.yml to the existing backend prov plugin
        provisioner:
            plugin_id: existing
            outputs:
                # You can put the launchpad yaml right here, or you can use This
                # approach where we point to a file that contains the yaml.
                mke_yaml: "file:{paths:project}/config/existing_cluster_launchpad.yml"


cli-options:
    accept-license": true
    disable-telemetry: true
