# This will tell mtt_mirantis to include mtt_mirantis/config/variation/ltc
variation: ltc
# This will tell mtt_mirantis to include mtt_mirantis/config/cluster/poc
cluster: poc
# This will tell mtt_mirantis to include mtt_mirantis/config/platform/public/ubuntu/18.04
platform: public/ubuntu/18.04

# release is set in both before/ and after/ folders
