
# background health poller
healthpoller:
    plugin_id: healthpoll_workload

    from_config: true

    poll:
        # How often should we poll for health
        period: 30


# sanity_kubernetes_deployment :: metta.plugin.workload:
stability_deployment:
    plugin_id: metta_kubernetes_deployment_workload

    labels:
      before: true
      after: true

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: "default"
    # define a  simple nginx workload called 'nginx-deployment'
    body:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.15.4
              ports:
              - containerPort: 80
