# use these for metta_mirantis presets
#
# This preset list sets the components for the testing cluster which is used
# by all upgrade environments.  The different environments keep the same
# confguration primarily, and differ only in presets.  This means that they
# share assets (terraform/ansible/launchpad) and are effectively declarative
# for their state and can be used indepentently.
#
# Each environment contains overrides for the release preset, so we leave that
# out.
#
# We keep presets which really should not change across environments here only
# so that no accidental platform, variation or cluster change happens across
# environments, which would completely destroy the cluster when terraform
# sees a big changes.
#
presets:
    # include metta_mirantis/config/variation/tal
    # Which combines terraform, ansible and launchpad.  You can configure
    # the variation from the variables/yml file.
    variation: tal
    # include metta_mirantis/config/cluster/poc
    # Which is a small cluster
    cluster: poc
    # include metta_mirantis/config/platform/public/ubuntu/20.04
    platform: public/ubuntu/20.04

    # @NOTE we don't use a 'release' preset here, as we put that into the
    #   ./before and ./after environment states
