mcr_repo_url: "https://s3.amazonaws.com/repos-internal.mirantis.com"
mcr_channel: test-19.03
mcr_version: 19.03.19-tp1
mke_image_repo: docker.io/mirantiseng
mke_version: 3.3.13-tp1
msr_image_repo: docker.io/mirantis
msr_version: 2.8.9
