# OS Platform to test on
platform_repo: public
platform: ubuntu_18.04
# Versions to test against.
mcr_channel: test
mcr_version: 19.03.15-rc1
mke_image_repo: docker.io/mirantiseng
mke_version: 3.3.8-rc1

# What version of Kubernetes should sonobuoy check conformance on.
# You should be able to leave this empty for auto-detection but it is not
# always reliable.
sonobuoy_kubernetes_version: v1.19.7
