# This config file is used only by this test suite.
# @see conftest.py as an example where a value is used to decide
#      if the cluster should be destroyed on exit
keep-on-finish: true
already-running: false
