presets:
    # This will tell metta to include metta/config/variation/ltc
    variation: tal
    # this will tell metta to include metta/config/release/patch/202101
    release: release/2021Q1
    # This will tell metta to include metta/config/cluster/poc
    cluster: poc
    # This will tell metta to include metta/config/platform/public/ubuntu/18.04
    platform: public/ubuntu/20.04

environments:
  # Create an environment called '2021Q1'
  sanity:
    bootstraps:
      metta:
      - metta_common
      - metta_ansible
      - metta_docker
      - metta_kubernetes
      - metta_terraform
      - metta_launchpad
      - metta_common_config
      - metta_mirantis_common
      - metta_mirantis_presets

    fixtures:
      from_config:
        # Load the fixtures from fixtures(.yml) source.
        label: fixtures
