cluster:
  name: "MKE-{{variables:mke_version}}-2"
azure:
  tenant: 8548a469-8c0e-4aa4-b534-ac75ca1e02f7
  subscription: 3959ec86-5353-4b0c-b5d7-3877122861a0
  resource_group: external-mirantis
  location: eastus
  sasname: mirantisarcsa
  sastoken: "?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2022-01-01T01:01:40Z&st=2021-09-16T17:01:40Z&spr=https&sig=kcApUSDiKO7DbaybMPDnxqyA67piMq9XVQe%2B%2BOak3%2B4%3D"

# This is set in the azurearc specific version config file.
# arc:
#   arc_platform_version: 1.2.0

# This is set in the MKE azure arc configuration
# partner-metadata:
#   path: "{{paths:mke}}/partner-metadata.yml"

cleanup:
  timeout: 1500
