
# azurearc :: metta.plugin.workload:
azurearc:
    plugin_id: metta_sonobuoy_workload

    # build the plugin from config, by passing a label/base to it
    from_config:
      # Sonobuoy will be told to read config from the sonobuoy.yml files
      label: sonobuoy


# Universal health poller for checking stability
healthpoller:
    plugin_id: healthpoll_workload

    from_config: true

    poll:
        # How often should we poll for health
        period: 15
