# This will tell mtt_mirantis to include mtt_mirantis/config/variation/ltc
variation: ltc
# this will tell mtt_mirantis to include mtt_mirantis/config/release/patch/202012
# This will get overridden in the MATRIX functionality
release: patch/202012
# This will tell mtt_mirantis to include mtt_mirantis/config/cluster/poc
# This will get overridden in the MATRIX functionality
cluster: poc
# This will tell mtt_mirantis to include mtt_mirantis/config/platform/public/ubuntu/18.04
# This will get overridden in the MATRIX functionality
platform: public/ubuntu/18.04
