manager_count: 5
manager_type: t3.xlarge
manager_volume_size: 100
worker_count: 20
worker_type: t3.large
worker_volume_size: 100
windows_worker_count: 0
msr_count: 5
msr_type: t3.xlarge
msr_volume_size: 100
