apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msr.fullname" . }}-notary-server
  labels:
    {{- include "msr.labels" . | nindent 4 }}
    app.kubernetes.io/component: notary-server
spec:
  replicas: {{ .Values.notaryServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "msr.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notary-server
  template:
    metadata:
      labels:
        {{- include "msr.labels" . | nindent 8 }}
        app.kubernetes.io/component: notary-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      containers:
        - name: notary-server
          securityContext: {}
          image: "{{ include "msr.imageRef" (list $ "notaryServer") }}"
          imagePullPolicy: {{ .Values.notaryServer.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
          env:
            - name: NOTARY_SERVER_STORAGE_DB_URL
              value: {{ include "msr.fullname" . }}-rethinkdb-proxy
            - name: NOTARY_SERVER_TRUST_SERVICE_HOSTNAME
              value: {{ include "msr.fullname" . }}-notary-signer
          volumeMounts:
            - name: certs
              mountPath: /certs
          # TODO:  See if we can get the health probe working.  There is an API endpoint:
          #        https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L234
          #        but I've not gotten it to succeed yet.  It seems to need mTLS to be active:
          #        "remote error: tls: bad certificate"
          # livenessProbe:
          #   httpGet:
          #     path: /_notary_server/health
          #     port: https
          #     scheme: HTTPS
          # readinessProbe:
          #   httpGet:
          #     path: /_notary_server/health
          #     port: https
          #     scheme: HTTPS
      volumes:
        - name: certs
          projected:
            sources:
            - secret:
                name: {{ include "msr.fullname" . }}-notary-server-cert
                items:
                - key: tls.key
                  path: notary-server/tls.key
                - key: tls.crt
                  path: notary-server/tls.crt
            - secret:
                name: {{ include "msr.fullname" . }}-notary-client-ca-cert
                items:
                - key: tls.crt
                  path: notary-server-client/ca.crt
            - secret:
                name: {{ include "msr.fullname" . }}-notary-server-to-signer-cert
                items:
                - key: tls.key
                  path: notary-signer-client/tls.key
                - key: tls.crt
                  path: notary-signer-client/tls.crt
            - secret:
                name: {{ include "msr.fullname" . }}-backend-server-ca-cert
                items:
                - key: tls.crt
                  path: notary-signer/ca.crt
            - secret:
                name: {{ include "msr.fullname" . }}-auth-signing-cert
                items:
                - key: tls.crt
                  path: auth/ca.crt
            - secret:
                name: {{ include "msr.fullname" . }}-rethinkdb-driver-client-cert-0
                items:
                - key: tls.key
                  path: rethink-client/tls.key
                - key: tls.crt
                  path: rethink-client/tls.crt
            - secret:
                name: {{ include "msr.fullname" . }}-rethinkdb-driver-ca-cert
                items:
                - key: tls.crt
                  path: rethink/ca.crt
