apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-notary-client-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-notary-client-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: "MSR Notary Client CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-notary-client-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-notary-client-ca-cert

{{- range list "nginx" "api" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" $ }}-{{ . }}-to-notary-cert
  labels:
    {{- include "msr.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" $ }}-{{ . }}-to-notary-cert
  commonName: "MSR {{ . }} to Notary mTLS Client"
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - client auth
  issuerRef:
    name: {{ include "msr.fullname" $ }}-notary-client-ca
    kind: Issuer
    group: cert-manager.io
{{- end }}
