apiVersion: v1
kind: Service
metadata:
  name: {{ include "msr.fullname" . }}-notary-signer
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7899
  selector:
    {{- include "msr.commonSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notary-signer
