backend:
    plugin_id: dummy
    outputs:
        ## as we want this dummy provisioner to
        mke_cluster:
            plugin_id: dict
            arguments:
                # the file contents are embedded here
                # the path to the file is defined in the variables config file
                data: "[file:{variables:launchpad_source_path}]"

    # which output in the dummy backend will we use
    launchpad_output: mke_cluster

cli-options:
    accept-license: true
    disable-telemetry: true

# This is the path to where mtt will write the values.  Even though we are
# using a passthrough file, we keep a copy of the last file used for diffs
# and restores, and also because it keeps the code the same for various
# backends which mau not start with a file
config_file: "{variables:files_path}/launchpad/{variables:files_prefix}.yaml"
