{{- range .Values.workloads }}
---
# Deployment for {{ .name }} workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npods-workload-{{ .name }}
  labels:
    app: npods-workload
    workload: npods-workload-{{ .name }}
spec:
  selector:
    matchLabels:
      app: npods-workload
      workload: npods-workload-{{ .name }}
  replicas: {{ .replicas }}
  template:
    metadata:
      labels:
        app: npods-workload
        workload: npods-workload-{{ .name }}
    spec:
      nodeSelector:
        com.docker.ucp.collection: shared
      containers:
      - name: npods-workload-{{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: 80
        env:
        - name: NPODS_NEXT_URI
          value: "http://npods-relay-{{ .name }}"
        - name: TEST_SLEEP
          value: {{ default "0s" .sleep | quote }}
        - name: TEST_CPU
          value: {{ default "0" .cpu | quote }}
        - name: TEST_RAM
          value: {{ default "0" .ram | quote }}
{{- end -}}
