# Environment: AFTER mirantis config
presets:
    # release preset is set per environment, so we ignore it heres
    # this will tell metta to include metta/config/release/patch/202106
    release: patch/202106 
