
# Polling health-checker
health:
    plugin_type: workload
    plugin_id: healthpoll

    # the healthpoller doesn't need anything else

# sanity_docker_run :: metta.plugin.workload:
sanity_docker_run:
    plugin_type: workload
    plugin_id: metta_docker_run

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    run:
        image: 'hello-world'

# sanity_kubernetes_deployment :: metta.plugin.workload:
sanity_kubernetes_deployment:
    plugin_type: workload
    plugin_id: metta_kubernetes_deployment

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: "default"
    body:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.15.4
              ports:
              - containerPort: 80

metrics-helm-workload:
    plugin_type: workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      bitnami: https://charts.bitnami.com/bitnami

    namespace: default
    chart: bitnami/metrics-server
    values:
      apiService.create: true
