dummy_1:
    # workload plugin id to be used
    plugin_id: mtt_dummy
    # config that will added to global config before being passes to the plugin
    config:
        # config label
        dummy:
            # some config values to show that you can override config
            one: one plugin_1

dummy_2:
    # workload plugin id to be used
    plugin_id: mtt_dummy
    # config that will added to global config before being passes to the plugin
    config:
        # config label
        dummy:
            # some config values to show that you can override config
            one: one from plugin_2
