{{/*
Expand the name of the chart.
*/}}
{{- define "enzi.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "enzi.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "enzi.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "enzi.labels" -}}
helm.sh/chart: {{ include "enzi.chart" . }}
{{ include "enzi.commonSelectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels common to multiple objects
*/}}
{{- define "enzi.commonSelectorLabels" -}}
app.kubernetes.io/name: {{ include "enzi.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Selector labels for worker pods
*/}}
{{- define "enzi.workerSelectorLabels" -}}
{{ include "enzi.commonSelectorLabels" . }}
app.kubernetes.io/component: worker
{{- end }}

{{/*
Selector labels for api pods
*/}}
{{- define "enzi.apiSelectorLabels" -}}
{{ include "enzi.commonSelectorLabels" . }}
app.kubernetes.io/component: api
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "enzi.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "enzi.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Probe to use for checking the status of the API deployment containers
*/}}
{{- define "enzi.apiHealthProbe" -}}
httpGet:
  path: /enzi/_ping
  port: 4443
  scheme: HTTPS
{{- end }}

{{/*
Build the image reference from the items contained in the "image" value.
*/}}
{{- define "enzi.imageRef" -}}

{{- $namespace := tpl .Values.image.namespace . -}}
{{- if $namespace -}}
{{- $namespace = print $namespace "/" -}}
{{- end -}}

{{- $tag := tpl .Values.image.tag . -}}
{{- if $tag -}}
{{- $tag = print ":" $tag -}}
{{- end -}}

{{ $namespace }}{{ .Values.image.repository }}{{ $tag }}
{{- end }}
