apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enzi.fullname" . }}-api-config
  labels:
    {{- include "enzi.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "auth-api-entrypoint.sh").AsConfig | indent 2 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enzi.fullname" . }}-api
  labels:
    {{- include "enzi.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.apiReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "enzi.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "enzi.apiSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "enzi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "enzi.imageRef" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: enzi
              containerPort: 4443  # enzi's default API port
          command: [ "/scripts/auth-api-entrypoint.sh" ]
          env:
            - name: DBHOST
              value: {{ tpl .Values.dbAddr . }}
            - name: DBPORT
              value: {{ .Values.dbPort | quote }}
            - name: TLSDIR
              value: /secrets/tls
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: scripts
              mountPath: /scripts
          livenessProbe:
{{ include "enzi.apiHealthProbe" . | indent 12 }}
          readinessProbe:
{{ include "enzi.apiHealthProbe" . | indent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: secrets
          projected:
            sources:
            - secret:
                name: {{ tpl .Values.tlsCertSecret . }}
                items:
                - key: tls.key
                  path: tls/key.pem
                - key: tls.crt
                  path: tls/cert.pem
            - secret:
                name: {{ tpl .Values.tlsCABundleSecret . }}
                items:
                - key: tls.crt
                  path: tls/ca.pem
        - name: scripts
          configMap:
            name: {{ include "enzi.fullname" . }}-api-config
            defaultMode: 0555
            items:
              {{- range tuple "auth-api-entrypoint.sh" }}
              - key: {{ . }}
                path: {{ . }}
              {{- end }}
