apiVersion: v1
kind: Service
metadata:
  name: {{ include "enzi.fullname" . }}
  labels:
    {{- include "enzi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: enzi
  selector:
    {{- include "enzi.apiSelectorLabels" . | nindent 4 }}
