apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-backend-server-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-backend-server-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: "MSR Backend-to-Frontend Server CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-backend-server-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-backend-server-ca-cert
