apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "msr.fullname" . }}-initialize
  labels:
    {{- include "msr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "9999"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "msr.fullname" . }}-initialize
      labels:
        {{- include "msr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: initialize-rethinkdb
          securityContext: {}
          image: "{{ include "msr.imageRef" (list $ "initializeJob") }}"
          imagePullPolicy: {{ .Values.initializeJob.image.pullPolicy }}
          command: ["/bin/sh", "-c", "msr db migrate && msr auth register https://${MSR_ENZI_HOST}/enzi"]
          env:
            - name: MSR_ENZI_HOST
              value: "{{ include "msr.fullname" . }}-enzi:{{ .Values.enzi.service.port }}"
            - name: MSR_ENZI_REGISTRATION_USERNAME
              value: "admin"
            - name: MSR_ENZI_REGISTRATION_PASSWORD
              value: "password"
            - name: MSR_ENZI_CA_CERT_FILE
              value: /certs/rethinkdb-client/ca.crt
            - name: MSR_ENZI_CLIENT_CA_CERT_FILE
              value: /certs/enziservice-client/ca.crt
            - name: MSR_RETHINKDB_ADDR
              value: "{{ .Release.Name }}-rethinkdb-proxy:{{ .Values.rethinkdb.ports.driver }}"
            - name: MSR_RETHINKDB_CLIENT_CERT_FILE
              value: /certs/rethinkdb-client/tls.crt
            - name: MSR_RETHINKDB_CLIENT_KEY_FILE
              value: /certs/rethinkdb-client/tls.key
            - name: MSR_RETHINKDB_CA_CERT_FILE
              value: /certs/rethinkdb/ca.crt
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          projected:
            sources:
              - secret:
                  name: "{{ include "msr.fullname" . }}-rethinkdb-driver-client-cert-0"
                  items:
                    - key: tls.key
                      path: rethinkdb-client/tls.key
                    - key: tls.crt
                      path: rethinkdb-client/tls.crt
                    - key: ca.crt
                      path: rethinkdb-client/ca.crt
              - secret:
                  name: "{{ include "msr.fullname" . }}-rethinkdb-driver-ca-cert"
                  items:
                    - key: ca.crt
                      path: rethinkdb/ca.crt
              - secret:
                  name: "{{ include "msr.fullname" . }}-enzi-client-cert"
                  items:
                    - key: ca.crt
                      path: enziservice-client/ca.crt
