# PKI for intra-cluster mTLS
# NB: Currently unused
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-cluster-root-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-cluster-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: "MSR RethinkDB Cluster CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---

# NB: Unused
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-cluster-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-rethinkdb-cluster-ca-cert

---

# NB: Unused
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-cluster-cert-0
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-cluster-cert-0
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - client auth
  - server auth
  dnsNames:
  - {{ include "msr.fullname" . }}-rethinkdb-cluster
  issuerRef:
    name: {{ include "msr.fullname" . }}-rethinkdb-cluster-ca
    kind: Issuer
    group: cert-manager.io

---

# PKI for driver server TLS auth

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-root-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: "MSR RethinkDB Driver CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-ca-cert

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-cert
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-cert
  commonName: "MSR RethinkDB Driver Service"
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - server auth
  dnsNames:
  - {{ .Release.Name }}-rethinkdb-proxy
  - localhost
  ipAddresses:
  - "127.0.0.1"
  - "::1"
  issuerRef:
    name: {{ include "msr.fullname" . }}-rethinkdb-driver-ca
    kind: Issuer
    group: cert-manager.io

---

# PKI for driver client authentication

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-client-root-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-client-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: "MSR RethinkDB Client CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-client-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-client-ca-cert

---

{{/*
  This cert is also used by eNZi as the API server cert. Eww.
  TODO(12factor)(ENGDTR-2290): make this cert no longer pull double-duty as
  the eNZi server cert.
*/}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-rethinkdb-driver-client-cert-0
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-rethinkdb-driver-client-cert-0
  commonName: "MSR RethinkDB Driver Client 0"
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - client auth
  - server auth
  dnsNames:
  - "{{ include "msr.fullname" . }}-enzi"
  issuerRef:
    name: {{ include "msr.fullname" . }}-rethinkdb-driver-client-ca
    kind: Issuer
    group: cert-manager.io
