
# Create an environment called 'cncf'
cncf:
  bootstraps:
    metta:
    - metta_common
    - metta_ansible
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets
    - metta_sonobuoy

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
