
# cncf :: metta.plugin.workload:
cncf:
    type: workload
    plugin_id: metta_sonobuoy_workload

    # build the plugin from this config, by passing this label/base to it
    from_config:
      # Sonobuoy will be told to read config from the sonobuoy yml files
      label: sonobuoy
