
# cncf :: metta.plugin.workload:
cncf:
    type: workload
    plugin_id: metta_sonobuoy_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    mode: certified-conformance

    kubernetes:
        version: v1.20.1

    plugin:
        plugins:
        - e2e
        envs:
        - e2e.E2E_EXTRA_ARGS=--non-blocking-taints=com.docker.ucp.manager
