{{- if .Values.trigger.threads }}
# Start relay threads using curl jobs
apiVersion: batch/v1
kind: Job
metadata:
  name: npod-trigger
spec:
  template:
    spec:
      containers:
      - name: trigger
        image: curlimages/curl
        command: ["bin/sh"]
        args:
        - "-c"
        - "for i in $(seq {{ default 1 .Values.trigger.start }} {{ default 1 .Values.trigger.threads }}); do curl -ssL http://npods-relay?thread=$1; echo \"Triggered $i\"; done"
      restartPolicy: Never
  completions: 1
{{- end }}