terraform:
    plans:
        prodeng:
            aws:
                v5: "{paths:mtt}/terraform/plans/prodeng/aws/v5"
        example:
            aws:
                v1_2: "{paths:mtt}/terraform/plans/example/aws/1.2"
