# All of the below config is read by the sonobuoy plugin, as directed in the
# fixtures.yml file.

results:
  # unique path for each retrieve (this path contains a space)
  path: "{{paths:project}}/results"

# Args for sonobuoy run
run:
  mode: certified-conformance
  rbac: Enable
  kubernetes-version: "{{variables:sonobuoy_kubernetes_version}}"
  level: debug

plugins:
  e2e:
    envs:
      E2E_EXTRA_ARGS: "--non-blocking-taints=com.docker.ucp.manager"
      # E2E_PARALLEL:          true
      # E2E_EXTRA_ARGS:        "--non-blocking-taints=com.docker.ucp.manager"
      # E2E_FOCUS:             "[Conformance]"
      # E2E_SKIP:              "[Disruptive]|NoExecuteTaintManager"
      # E2E_SKIP: ""
      # E2E_USE_GO_RUNNER:     true
      # SONOBUOY_K8S_VERSION:  "{{variables:sonobuoy_kubernetes_version}}"
