# All of the below config is read by the sonobuoy plugin, as directed in the
# fixtures.yml file.

mode: certified-conformance

kubernetes:
  # Pull the kubernetes version from the variables config file
  version: "{{variables:sonobuoy_kubernetes_version}}"

results:
  # unique path for each retrieve (this path contains a space)
  path: "{{paths:project}}/results"

plugin:
    plugins:
    - e2e
    envs:
    - e2e.E2E_EXTRA_ARGS=--non-blocking-taints=com.docker.ucp.manager
