# All of the below config is read by the sonobuoy plugin, as directed in the
# fixtures.yml file.

results:
  # unique path for each retrieve (this path contains a space)
  path: "{{paths:project}}/results"

# Args for sonobuoy run
run:
  mode: certified-conformance
  kubernetes-version: "{{variables:sonobuoy_kubernetes_version}}"
  ssh-key: "{{terraform:vars.ssh_key_file_path}}"
  # we should get this from hosts or something.
  ssh-user: ubuntu

plugins:
  e2e:
    envs:
      E2E_EXTRA_ARGS: "--non-blocking-taints=com.docker.ucp.manager --progress-report-url=http://localhost:8099/progress"
