# This will tell mtt_mirantis to include mtt_mirantis/config/variation/ltc
variation: ltc
# this will tell mtt_mirantis to include mtt_mirantis/config/release/patch/202101
release: patch/202012
# This will tell mtt_mirantis to include mtt_mirantis/config/cluster/poc
cluster: poc
# This will tell mtt_mirantis to include mtt_mirantis/config/platform/public/ubuntu/18.04
platform: public/ubuntu/18.04
