# This config ise used primarily for overrides in other config.
# It is handy because then we can focus on this file


# Used in terraform resource tagging
user: "{user:id?anon}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "ltc"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "default"

# A generic project/user id that we reuse across the configuration
id: "{user:id?user}-mtt-ltc-demo"
# where the ltc variation should keep runtime paths like terraform state
files_path: "{paths:project}"
# Prefix all resource files we create with this, which allows multiples and id
files_prefix: "{id}"
# Prefix all created resources with this so that we can id them
# this is different than {id} to allow character limits to be avoided
resource_prefix: "{user:id?user}-mtt"

# AWS region for resources
aws_region: us-east-2

# perhaps not needed any more
cluster_name: "{id}"
# used to tag cluster resources for expiry
expire_duration: 72h

# The Linux platform to use for manager/worker/DTR replica nodes
platform_repo: public
platform: ubuntu_18.04

# SSH/RDP admin passwords for nodes
admin_password: orcaorcaorca
windows_administrator_password: "tfaws,,ABC..Example"
