

# terraform :: metta.plugin.provisioner:
terraform:
    plugin_id: metta_terraform_provisioner

    # Terraform will configure itself from the ./terraform.yml file
    # This is actually its default but this demonstrates that we have
    # the option.
    from_config:
        label: terraform
        # base: some.path.in.the.file

# ansible :: metta.plugin.provisioner:
ansible:
    plugin_id: metta_ansiblecliplaybook_provisioner

    # This directs ansible configuration to come from the ansible.yml file
    from_config:
        label: ansible

# Here we use a combo provisioner with  a high priority to act as a primary
# provisioner to manage all of the others
#
# @NOTE you want this plugin to be a higher priority than the others
#   so that a get_plugins(provisioner) retrieves this one first.
combo:
    plugin_id: combo_provisioner
    priority: 95

    # tell the plugin to load config from "here"
    from_config: true

    backends:
    # Ordered list of backend instances
    - instance_id: terraform
    - instance_id: ansible

# Universal health poller for checking stability
healthpoller:
    plugin_id: healthpoll_workload

    from_config: true

    poll:
        # How often should we poll for health
        period: 15

ansibledebug:
  plugin_id: metta_ansible_clicore_ansibleplaybook_workload
  labels:
    primary: True

  # tell the plugin to load config from "here"
  from_config: true

  playbook:
    path: "{{variables:files_path}}/{{variables:files_prefix}}.ansibleping.playbook.yml"
    contents:
    - name: Debugs all targets
      hosts: all
      tasks:
        - setup: {}
        - debug: {}
        - ping: {}
