
# just any generic helm chart run
metrics-helm-workload:
    plugin_type: workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      bitnami: https://charts.bitnami.com/bitnami

    namespace: default
    chart: bitnami/metrics-server
    values:
      apiService.create: true


healthpoller:
    plugin_type: workload
    plugin_id: healthpoll

    from_config: true

    poll: 
        # How often should we poll for health
        period: 600
