# Longevity test settings
#
# Currenlty we only have one test function so
# we just have one set of configurations for it.
#
# Here define governance that is used in only
# test_longevity/test_longevity.py
#

# How frewuently to report on health
period: 60
# How many health reports to perform before moving on
count: 10
