# An array of objects which describe individual deployments
# which will create pods of relay nodes, a paired service and
# a trigger job to create workload.
workloads: []
# - name: default
#   image: msr.ci.mirantis.com/jnesbitt/n-pods-app:0.16
#   replicas: 1000
#   sleep: 0s
#   cpu: 100
#   ram: 8192
#   threads: 100
