# This config is used primarily for overrides in other config.
# It is handy because then we can focus on this file

# WHAT CAN I PUT HERE?
#
# If you are using the ltc variation, then look at mtt/config/variations/ltc
# at the variables file there, and how variables:X are injected into the other config
# files there.
# Note also that values in mtt may tell mtt to load more variables data from
# other folders in mtt/config. You can still override those values here

# Used in terraform resource tagging (user:id gets set in conftest.py)
user: "{user:id?anon}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "ltc"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "PRODENG"

# A generic project/user id that we reuse across the configuration
id: "{user}-playground"
# where the ltc variation should keep runtime paths like terraform state
files_path: "{paths:project}"
# Prefix all resource files we create with this, which allows multiples and id
files_prefix: "{id}"
# Prefix all created resources with this so that we can id them
# this is different than {id} to allow character limits to be avoided
resource_prefix: "{user}-mtt"

# AWS region for resources
aws_region: us-east-2

# perhaps not needed any more
cluster_name: "{id}"
# used to tag cluster resources for expiry
expire_duration: 72h

# SSH/RDP admin passwords for nodes
admin_password: orcaorcaorca
windows_administrator_password: "tfaws,,ABC..Example"

terraform_is_provisioned: false
# If true, then launchpad will skip the prepare/apply on the backend
launchpad_is_installed: false
# If true, then launchpad will skip the install

mcr_channel: test
mcr_version: 20.10.0-rc1
mke_image_repo: docker.io/mirantiseng
mke_version: 3.4.0-tp2
msr_image_repo: docker.io/mirantiseng
msr_version: 2.9.0-rc1
