# This config is used primarily for overrides in other config.
# It is handy because then we can focus on this file

# WHAT CAN I PUT HERE?
#
# If you are using the tal variation, then look at metta_mirantis/config/variations/tal
# at the variables file there, and how variables:X are injected into the other config
# files there.
# Note also that values in metta may tell metta to load more variables data from
# other folders in metta_mirantis/config. You can still override those values here

# Used in terraform resource tagging (user:id gets set in conftest.py)
user: "{{user:id?anon}}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "msronk8s"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "TAR-TLNG-ATMTN"

# A generic project/user id that we reuse across the configuration
id: "{{user}}-{{task}}"

# where the tal variation should keep runtime paths like terraform state
files_path: "{{paths:project}}/.metta"

# Increase spot price for longevity
# pct_over_spot_price: 33

# used to tag cluster resources for expiry
# expire_duration: 720h

# Don't bring up any MSR nodes, as we will install using helm
msr_count: 0

# Tag any resources with the suite name, and metta preset information
extra_tags:
  metta-suite: "{{task}}"
  metta-mirantis.preset.variation: "{{mirantis:presets.variation}}"
  metta-mirantis.preset.cluster: "{{mirantis:presets.cluster}}"
  metta-mirantis.preset.platform: "{{mirantis:presets.platform}}"
  metta-mirantis.preset.release: "{{mirantis:presets.release}}"
  contact: jnesbitt@mirantis.com
  team: PRODENG
  pet: true
