

# loki workload : monitoring tooling workload
loki-workload:
    plugin_id: metta_kubernetes_helm_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      grafana: https://grafana.github.io/helm-charts

    namespace: loki
    chart: grafana/loki-stack

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.loki.yaml"
    values:

      loki:
        nodeSelector:
          com.docker.ucp.collection: system

      promtail:
        nodeSelector:
          com.docker.ucp.collection: system

      fluent-bit:
        nodeSelector:
          com.docker.ucp.collection: system

      grafana:
        enabled: true
        image:
          tag: 7.4.5

        adminUser: admin
        adminPassword: admin

        nodeSelector:
          com.docker.ucp.collection: system

        imageRenderer:
          enabled: true

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default

        dashboards:
          default:
            node-exporter-server-metrics:
              title: NodeExporter
              folder: general
              gnetId: 11952
              version: 1
              datasource: Prometheus
              refresh: 10s
              time:
                from: "now-30m"
                to: "now"

      prometheus:
        enabled: true

        nodeSelector:
          com.docker.ucp.collection: system

        alertmanager:
          persistentVolume:
            enabled: false
        server:
          persistentVolume:
            enabled: false
