# NPods test suite configuration
#
# Configuration from this file is used only in the test suite for npods, where
# values are used to configure how the tests run.
#

# Control cluster monitoring
monitoring:
  # enable the loki helm chart
  enable: true

workload:
  # default/template values for the npods helm workload yaml
  #
  # Here we set only a modest workload as we want the test case itself to
  # apply a load by scaling up the helm chart.  The values below are used
  # to configure the deployment/pod/service settings for the app, and to
  # provide an early health check.

  scale:
    name: 'npods-workload-default'
    replicas: 100
    image: 'msr.ci.mirantis.com/jnesbitt/n-pods-app:0.18'
    sleep: '10ms'
    cpu: '300'
    ram: '8192'
    threads: 100

  stability:
    name: 'npods-workload-default'
    replicas: 100
    image: 'msr.ci.mirantis.com/jnesbitt/n-pods-app:0.18'
    sleep: '10ms'
    cpu: '300'
    ram: '8192'
    threads: 100


tests:
  # Control the scaling test
  scale:
    duration: 30

  # Configure the stability test
  stability:
    duration: 60
