# This config is used primarily for overrides in other config.
# It is handy because then we can focus on this file

# WHAT CAN I PUT HERE?
#
# If you are using the ltc variation, then look at metta/config/variations/ltc
# at the variables file there, and how variables:X are injected into the other config
# files there.
# Note also that values in metta may tell metta to load more variables data from
# other folders in metta/config. You can still override those values here

# Used in terraform resource tagging (user:id gets set in conftest.py)
user: "{{user:id?anon}}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "upgrade"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "TAR-TLNG-ATMTN"

# A generic project/user id that we reuse across the configuration
id: "{{user}}-{{task}}"

# where the ltc variation should keep runtime paths like terraform state
files_path: "{{paths:project}}/.metta"

# Tag any resources with the suite name, and metta preset information
extra_tags:
  metta-suite: "{{task}}"
  metta-mirantis.preset.variation: "{{mirantis:presets.variation}}"
  metta-mirantis.preset.cluster: "{{mirantis:presets.cluster}}"
  metta-mirantis.preset.platform: "{{mirantis:presets.platform}}"

# This test relies on mirantis presets for base cluster and puts variable
# overrides into the ./after/variables.yml and /before/variables.yml files
# to define before and after states.
