
# npods-support - supporting network and namespace for npods-workload
npods-workload: 
    type: metta.plugin.workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: npods
    chart: "{{paths:project}}/npods-helm"

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.npods.yaml"
    values:
      trigger:
        # start with 0 threads, we will modify this and re-run
        threads: 400
      workloads:
      # Heavier workload, starting at 100 pods
      - name: heavy
        image: mirantiseng/testeng-referenceapp:npods_0.16
        replicas: 100
        sleep: 0s 
        cpu: 100
        ram: 8192
      # leander workload, starting at 100 pods
      - name: lean
        image: mirantiseng/testeng-referenceapp:npods_0.16
        replicas: 100
        sleep: 1s 
        cpu: 0
        ram: 0


# loki workload : monitoring tooling workload
loki-workload:
    type: metta.plugin.workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      grafana: https://grafana.github.io/helm-charts

    namespace: loki
    chart: grafana/loki-stack

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.loki.yaml"
    values:

      grafana:
        enabled: true
      prometheus:
        enabled: true
        alertmanager:
          persistentVolume:
            enabled: false
        server:
          persistentVolume:
            enabled: false
