
# npods-support - supporting network and namespace for npods-workload
npods-workload: 
    type: metta.plugin.workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: npods
    chart: "{{paths:project}}/npods-helm"

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.npods.yaml"
    values:
      triggers:
        - name: initial
          # start with 10 threads, we will manually run triggers so that we can scale the volume
          threads: 100
      workloads:
      # Heavier workload, simulate some computation
      - name: heavy
        image: msr.ci.mirantis.com/jnesbitt/n-pods-app:0.17
        replicas: 100
        sleep: 10ms 
        cpu: 300
        ram: 8192
      # light workload - simulate something with a delay like a db retrieval
      - name: lean
        image: msr.ci.mirantis.com/jnesbitt/n-pods-app:0.17
        replicas: 100
        sleep: 500ms 
        cpu: 10
        ram: 512


# loki workload : monitoring tooling workload
loki-workload:
    type: metta.plugin.workload
    plugin_id: metta_kubernetes_helm

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      grafana: https://grafana.github.io/helm-charts

    namespace: loki
    chart: grafana/loki-stack

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.loki.yaml"
    values:

      grafana:
        enabled: true
        image:
          tag: 7.4.5

        adminUser: admin
        adminPassword: admin

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: false
                options:
                  path: /var/lib/grafana/dashboards/default

        dashboards:
          default:
            node-exporter-server-metrics:
              folder: general
              gnetId: 405
              version: 8
              datasource: Prometheus

      prometheus:
        enabled: true
        alertmanager:
          persistentVolume:
            enabled: false
        server:
          persistentVolume:
            enabled: false
