
# Create an environment called 'sanity'
sanity:
  # Environment plugin to use
  plugin_id: metta_state_environment

  # this tells metta that this config block should be passed to the plugin
  # for config use (you could tell it to load from a different source.)
  from_config: true

  bootstraps:
    - metta_common
    - metta_health
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
