
# sanity_docker_run :: metta.plugin.workload:
sanity_docker_run:
    type: metta.plugin.workload
    plugin_id: metta_docker_run

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    run:
        # https://docker-py.readthedocs.io/en/stable/containers.html
        image: 'hello-world'
