
my_messages:
    plugin_type: client
    plugin_id: my_client

    # for plugisn that take a label/key pair as factory arguments, this points
    # them to this configuration.
    from_config: true

    messages:
    - Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro.
    - De carne lumbering animata corpora quaeritis.
    - Summus brains sit​​, morbo vel maleficia?
    - De apocalypsi gorger omero undead survivor dictum mauris.
    - Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus.
    - Resi dentevil vultus comedat cerebella viventium
