
my_messages:
    type: metta.plugin.client
    plugin_id: my_client

    arguments:
      label: fixtures
      base: my_messages

    messages:
    - Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro.
    - De carne lumbering animata corpora quaeritis.
    - Summus brains sit​​, morbo vel maleficia?
    - De apocalypsi gorger omero undead survivor dictum mauris.
    - Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus.
    - Resi dentevil vultus comedat cerebella viventium
