backend:
    plugin_id: mtt_terraform
    output: mke_cluster_yaml

cli-options:
    accept-license": true
    disable-telemetry: true

cluster_name: "{variables:id}"
config_file: "{variables:files_path}/launchpad/{cluster_name}.yaml"
