---
- name: Check if swarm is enabled on leader
  ansible.builtin.command: docker info --format {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: leader_swarm_status

- name: Initialize swarm
  ansible.builtin.command: docker swarm init
  register: swarm_init
  when: leader_swarm_status.stdout == 'inactive'

- name: Get manager token
  ansible.builtin.command: docker swarm join-token manager
  register: manager_join_token

- set_fact:
    swarm_join_manager: "{{ manager_join_token.stdout_lines[2] | trim }}"

- name: Get worker token
  ansible.builtin.command: docker swarm join-token worker
  register: worker_join_token

- set_fact:
    swarm_join_worker: "{{ worker_join_token.stdout_lines[2] | trim }}"
