{{- if and .Values.proxy.driverTLS.enabled (or .Values.proxy.driverTLS.key .Values.proxy.driverTLS.cert) }}
{{- if not (and .Values.proxy.driverTLS.key .Values.proxy.driverTLS.cert) }}
  {{- fail "Must specify both 'driverTLS.key' and 'driverTLS.cert', or neither of them." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rethinkdb.driverTLSSecretName" . }}
  labels:
    app: {{ template "rethinkdb.name" . }}
    chart: {{ template "rethinkdb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/tls"
data:
  tls.key: {{ .Values.proxy.driverTLS.key | b64enc | quote }}
  tls.crt: {{ .Values.proxy.driverTLS.cert | b64enc | quote }}
{{- end }}

---

{{- if .Values.rethinkdbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rethinkdb.fullname" . }}-admin-creds
  labels:
    app: {{ template "rethinkdb.name" . }}
    chart: {{ template "rethinkdb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/basic-auth"
data:
  username: {{ "admin" | b64enc }}
  password: {{ .Values.rethinkdbPassword | b64enc | quote }}
{{- end }}

---

{{- if and (include "rethinkdb.driverTLSMutualSecretName" .) (.Values.proxy.driverTLS.mutual.cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rethinkdb.driverTLSMutualSecretName" . }}
  labels:
    app: {{ template "rethinkdb.name" . }}
    chart: {{ template "rethinkdb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .Values.proxy.driverTLS.mutual.cert | b64enc | quote }}
{{- end }}

---

{{- if and .Values.cluster.clusterTLS.enabled (or .Values.cluster.clusterTLS.key .Values.cluster.clusterTLS.cert .Values.cluster.clusterTLS.cacert) }}
{{- if not (and .Values.cluster.clusterTLS.key .Values.cluster.clusterTLS.cert .Values.cluster.clusterTLS.cacert) }}
  {{- fail "Must specify all of ['clusterTLS.key', 'clusterTLS.cert', and 'clusterTLS.cacert'], or none of them." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rethinkdb.clusterTLSSecretName" . }}
  labels:
    app: {{ template "rethinkdb.name" . }}
    chart: {{ template "rethinkdb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/tls"
data:
  tls.key: {{ .Values.cluster.clusterTLS.key | b64enc | quote }}
  tls.crt: {{ .Values.cluster.clusterTLS.cert | b64enc | quote }}
  ca.crt: {{ .Values.cluster.clusterTLS.cacert | b64enc | quote }}
{{- end }}
