{{- if .Values.proxy.driverTLS.enabled }}
{{- if not (or .Values.proxy.driverTLS.secretName .Values.proxy.driverTLS.cert .Values.proxy.driverTLS.key) }}
  {{- fail "driverTLS is enabled, but neither a secret name nor inline credential data were provided." }}
{{- end }}
{{- end }}

{{- if .Values.cluster.clusterTLS.enabled }}
{{- if not (or .Values.cluster.clusterTLS.secretName .Values.cluster.clusterTLS.cert .Values.cluster.clusterTLS.key .Values.cluster.clusterTLS.cacert) }}
  {{- fail "clusterTLS is enabled, but neither a secret name nor inline credential data were provided." }}
{{- end }}
{{- end }}
