apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-nginx-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-nginx-ca-cert
  duration: 8760h # 365d
  renewBefore: 24h
  commonName: nginx
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-nginx-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-nginx-ca-cert

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-nginx-cert-0
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-nginx-cert-0
  commonName: "MSR Web Interface"
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - server auth
  dnsNames:
  - nginx
  - localhost
  ipAddresses:
  - "127.0.0.1"
  - "::1"
  issuerRef:
    name: {{ include "msr.fullname" . }}-nginx-ca
    kind: Issuer
    group: cert-manager.io
