apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.servicename }}
  name: {{ .Values.service.servicename }}
{{- else }}
  name: {{ include "msr.fullname" . }}
{{- end }}
  labels:
    {{- include "msr.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (eq .Values.service.type "LoadBalancer" "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges:
  {{- with .Values.service.loadBalancerSourceRanges }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalHTTPPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.externalHTTPSPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "msr.nginxSelectorLabels" . | nindent 4 }}
