# OS Platform to test on
platform_repo: public
platform: ubuntu_20.04
# Versions to test against.
mcr_version: 20.10.7
mke_version: 3.4.6

# What version of Kubernetes should sonobuoy check conformance on.
sonobuoy_kubernetes_version: v1.20.11
