# OS Platform to test on
platform_repo: public
platform: ubuntu_20.04
# Versions to test against.
#mcr_repo_url: "https://s3.amazonaws.com/repos-internal.mirantis.com"
mcr_channel: stable
mcr_version: 20.10.7
mke_image_repo: docker.io/mirantis
mke_version: 3.4.5

# What version of Kubernetes should sonobuoy check conformance on.
sonobuoy_kubernetes_version: v1.20.8
