
# Create an environment called 'default'
default:
  # This environments only adds the dummy bootstrap which is used to discover
  # the dummy plugins, which are the only plugins we use in this suite.
  bootstraps:
    metta:
    - metta_dummy

  # This environment contains fixtures, defined in configuration.
  # The from_config label tesll metta to look in the 'fixtures.yml'
  # file for a list of fixtures to create.
  fixtures:
    from_config:
      label: fixtures
