# Environment Fixtures
#
# Here we define a set of dummy fixtures.  We use dummies here so that we can
# have a lightweight set of plugins that have no external dependencies just for
# the purpose of demonstrating and testing metta functionality.
#
# Dummy plugins take configuration inline and exhibit proper interfaces, but
# do nothing other than return fixtures that they were programmed with.
# These fixtures are used in test functions.
#
---
# prov1: A dummy provisioner (used to demo provisoiner behaviour.)
#
# The provisioner itself contains 2 fixtures:
#
# 1. client1 (Client) A dummy client which does nothing, but does provide access
#    to two output fixtures of its own.  The dummy client plugin allows defining
#    outputs in config.
#    Both Outputs just contain static contents, one string, and the other a dict.
#
# 2. An ouput plugin configured directl to contain a dict.
prov1:
  type: PROVISIONER
  plugin_id: dummy

  arguments:
    fixtures:

      client1:
        type: client
        plugin_id: dummy

        arguments:
          fixtures:

            output1:
              type: output
              plugin_id: text

              arguments:
                text: prov client one output one

            output2:
              type: metta.plugin.output
              plugin_id: dict

              arguments:
                data:
                  '1':
                    '1': prov client one output two data one.one

      output1:
        type: metta.plugin.output
        plugin_id: text

        arguments:
          text: prov dummy output one

# Two dummy workload plugins are defined here which can be access directly
# Both do nothing but the second contains two fixtures of its own, a client
# and an output.

work1:
  type: metta.plugin.workload
  plugin_id: dummy

work2:
  type: workload
  plugin_id: dummy

  arguments:
    fixtures:

      output1:
        type: output
        plugin_id: text

        arguments:
          text: workload two dummy output one

      client1:
        type: client
        plugin_id: dummy
