
# Create an environment called 'before'
#
# This is the initial upgrade state environment.  This creates a full testing
# environment which matches our starting start.  The next state is a different
# environment that will share a lot of settings, and will use the same
# launchpad/terraform/ansible assets - and therefore will modify this testing
# cluster.
#
before:
  bootstraps:
    metta:
    - metta_common
    - metta_ansible
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  config:
    sources:
      project-config-before:
        plugin_id: path
        priority: 80
        path: "{paths:project-config}/before"

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures

# Create an environment called 'after'
#
# After mimics before in all settings except for those which come from the
# metta_mirantis presets.  This allows a divergence at presets, using the
# same launchpad/terraform/ansible assets - so when we switch environments
# we can apply a delta to achieve a declarative state.
#
after:
  bootstraps:
    metta:
    - metta_common
    - metta_ansible
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  config:
    sources:
      project-config-after:
        plugin_id: path
        priority: 80
        path: "{paths:project-config}/after"

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
