
# Create an environment called 'before'
#
# This is the initial upgrade state environment.  This creates a full testing
# environment which matches our starting start.  The next state is a different
# environment that will share a lot of settings, and will use the same
# launchpad/terraform/ansible assets - and therefore will modify this testing
# cluster.
#
before:
  bootstraps:
    metta:
    - metta_common
    - metta_ansible
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  config:
    sources:
      beforepreset-config:
        plugin_id: dict
        priority: 75
        data:
          metta_mirantis:
            # use these for metta_mirantis presets
            presets:
                # this will tell metta to include metta/config/release/release/2021Q1-rc1
                # Which has the 2-21 Q1 release but RC1 versions
                release: release/2021Q1-rc1

          # The above preset is equivalent to the following:
          # variables:
          #     mcr_channel: test
          #     mcr_version: 20.10.0-rc2
          #     mke_image_repo: docker.io/mirantiseng
          #     mke_version: 3.4.0-rc1
          #     msr_image_repo: docker.io/mirantiseng
          #     msr_version: 2.9.0-rc1
          #
          # you could remove the metta_mirantis preset and use this instead

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures

# Create an environment called 'after'
#
# After mimics before in all settings except for those which come from the
# metta_mirantis presets.  This allows a divergence at presets, using the
# same launchpad/terraform/ansible assets - so when we switch environments
# we can apply a delta to achieve a declarative state.
#
after:
  bootstraps:
    metta:
    - metta_common
    - metta_ansible
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  config:
    sources:
      after-preset-config:
        plugin_id: dict
        priority: 75
        data:
          metta_mirantis:
            # use these for metta_mirantis presets
            presets:
                # this will tell metta to include metta/config/release/release/2021Q1
                # This preset contains the latest 2021Q1 definitions
                release: release/2021Q1

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
