
# launchpad :: metta.plugin.provisioner:
terraform:
    type: metta.plugin.provisioner
    plugin_id: metta_terraform

    # Tell terraform to configure itself from the ./terraform.yml file
    # This is actually its default but this demonstrates that we have
    # the option of setting any config path desired, including that we
    # could embed the terraform.yml file here.
    from_config:
        label: terraform
        # base: some.path.in.the.terraform.file

# ansible :: metta.plugin.provisioner:
ansible:
    type: metta.plugin.provisioner
    plugin_id: metta_ansible

    # build the plugin from this config, by passing this label/base to it
    from_config: true

# launchpad :: metta.plugin.provisioner:
launchpad:
    type: metta.plugin.provisioner
    plugin_id: metta_launchpad

    # Pass these values to the provisioner constructor.  The launchpad
    # constructor accepts override for "where to get config".  The values
    # here tell it to look back in this same location for config, instead of
    # its default of looking in the ./launchpad.yml file
    # build the plugin from this config, by passing this label/base to it
    from_config: true

    # Declare which output from the environment will give us our launchpad yml
    # The output needs to exist by the time the launchpad provisioner .apply()
    # runs.
    source_output:
      instance_id: mke_cluster

    cli-options:
        accept-license: true
        disable-telemetry: true

    # To allow pytest and mettac an other scripts to operate in a subfolder, but
    # to allow us to keep relative paths for things like the working dir,
    # we pass in an optional root path which tells the plugin that any relative
    # paths are to be based on the root path.
    #
    # @NOTE config_file below has its own rules for relative paths below
    root:
      path: "{paths:project}"

    # indicate that launchpad should be run in a particular path as a subprocess
    # CHDIR.  This can be needed if for example an ssh key path is relative to a
    # certain path.
    working_dir: ./tf_prodeng_plan

    # tell the plugin to put the launchpad yml
    #
    # @NOTE that relative paths are assumed to be relative to the working_dir
    #   Basically a decision had to be made on the meaning of a relative path.
    config_file: ./metta-demo.yaml



# sanity_docker_run :: metta.plugin.workload:
sanity_docker_run:
    type: metta.plugin.workload
    plugin_id: metta_docker_run

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    run:
        image: 'hello-world'

# sanity_kubernetes_deployment :: metta.plugin.workload:
sanity_kubernetes_deployment:
    type: metta.plugin.workload
    plugin_id: metta_kubernetes_deployment

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: "default"
    body:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.15.4
              ports:
              - containerPort: 80
