apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-registry-server-cert
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-registry-server-cert
  commonName: "MSR Registry Server"
  duration: 4380h
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - "{{ include "msr.fullname" . }}-registry"
    - "{{ include "msr.fullname" . }}-registry.{{ .Release.Namespace }}.svc"
    - localhost
  ipAddresses:
    - "127.0.0.1"
    - "::1"
  issuerRef:
    name: {{ include "msr.fullname" . }}-backend-server-ca
    kind: Issuer
    group: cert-manager.io
