# This config is used primarily for overrides in other config.
# It is handy because then we can focus on this file

# WHAT CAN I PUT HERE?
#
# If you are using the tal variation, then look at metta_mirantis/config/variations/tal
# at the variables file there, and how variables:X are injected into the other config
# files there.
# Note also that values in metta may tell metta to load more variables data from
# other folders in metta_mirantis/config. You can still override those values here

# Used in terraform resource tagging (user:id gets set in conftest.py)
user: "{{user:id?anon}}"
#  arbitrary yet unique string which represents the deployment, eg, 'refactor', 'unicorn', 'stresstest'.
task: "altrepo"
# One of the official cost-tracking project names. Without this, your cluster may get terminated without warning.
project: "TAR-TLNG-ATMTN"

# A generic project/user id that we reuse across the configuration
id: "{{user}}-{{task}}"

# where the tal variation should keep runtime paths like terraform state
files_path: "{{paths:project}}/.metta"

# Tag any resources with the suite name, and metta preset information
extra_tags:
  metta-suite: "{{task}}"
  metta-mirantis.preset.variation: "{{mirantis:presets.variation}}"
  metta-mirantis.preset.cluster: "{{mirantis:presets.cluster}}"
  metta-mirantis.preset.platform: "{{mirantis:presets.platform}}"
  purpose: "Testing install without dockerhub"


mcr_repo_url: "https://repos.mirantis.com/"
mcr_channel: stable
mcr_version: 20.10.4
mke_image_repo: msr.ci.mirantis.com/prodeng
mke_version: 3.4.0-tp9-56-g6143a4817
# msr_image_repo: msr.ci.mirantis.com/prodeng
# msr_version: 2.9.1-tp1-bb9f32af

# mcr_repo_url: "https://repos.mirantis.com/"
# mcr_channel: stable
# mcr_version: 20.10.0
# mke_image_repo: docker.io/mirantis
# mke_version: 3.4.0
# msr_image_repo: docker.io/mirantis
# msr_version: 2.9.0

# Let's start off just testing MKE
msr_count: 0

mke_install_defaultorchestrator: swarm
