# use these for metta_mirantis presets
#
# This preset list sets the components for the testing cluster which is used
# by all upgrade environments.  The different environments keep the same
# confguration primarily, and differ only in presets.  This means that they
# share assets (terraform/ansible/launchpad) and are effectively declarative
# for their state and can be used indepentently.
#
# Each environment contains overrides for the release preset, so we leave that
# out.
presets:

    # release preset is set per environment, so we ignore it heres
    # this will tell metta to include metta/config/release/release/2021Q1
    release: release/2021Q1
