{{/*
DNS name for resolving the scanningstore server service
*/}}
{{- define "msr.scanningstore.svc" }}
{{- /* Invoke the Bitnami Common fullname template with an approximation of the subchart context. */}}
{{- include "common.names.fullname" (mergeOverwrite (deepCopy .) (dict "Values" (set (deepCopy .Values.postgresql) "global" .Values.global))) }}
{{- end }}

{{/*
VolumeProjection for the scanningstore TLS client cert and server CA.

The executables currently hardcoded to load these files from fixed absolute
paths, so this volume must be mounted into each container at /config.
*/}}
{{- define "msr.scanningstore.clienttls.volumeProjection" -}}
- secret:
    name: {{ include "msr.fullname" . }}-scanningstore-client-cert
    items:
      - key: tls.crt
        path: postgres_client-cert.pem
      - key: tls.key
        path: postgres_client-key.pem
        mode: 0600
      - key: ca.crt
        path: postgres_ca-cert.pem
{{- end }}
