---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-scanningstore-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-scanningstore-ca-cert
  duration: 17520h # 2 years
  renewBefore: 24h
  commonName: "MSR scanningstore PostgreSQL CA"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - digital signature
  - key encipherment
  - cert sign
  - client auth
  - server auth
  issuerRef:
    name: {{ include "msr.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "msr.fullname" . }}-scanningstore-ca
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "msr.fullname" . }}-scanningstore-ca-cert
