# The bitnami/postgresql chart has a limitation that the client CA cert must be
# located in the same secret as the server keypair. It is infeasible to get
# cert-manager to create a secret containing both a keypair issued by one CA
# and an unrelated PKI's CA cert. So the server and client certs will both be
# issued by the same CA.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "msr.fullname" . }}-scanningstore-client
  labels:
    {{- include "msr.labels" . | nindent 4 }}
spec:
  secretName: {{ include "msr.fullname" . }}-scanningstore-client-cert
  duration: 8760h # 365 days
  renewBefore: 24h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
  - client auth
  commonName: "fuzzomatic"
  issuerRef:
    name: {{ include "msr.fullname" . }}-scanningstore-ca
    kind: Issuer
    group: cert-manager.io
