
# Create an environment called 'stability'
stability:
  bootstraps:
    metta:
    - metta_common
    - metta_health
    - metta_docker
    - metta_kubernetes
    - metta_terraform
    - metta_ansible
    - metta_launchpad
    - metta_common_config
    - metta_mirantis_common
    - metta_mirantis_presets

  config:
    sources:
      # include Environemnt variables as a source of config if they use the format
      # METTA_LABEL[_STEP]*
      # config.get(mylabel).get(one.two.three) would be METTA_MYLABEL_ONE_TWO_THREE
      metta-env:
        plugin_id: env-specific
        priority: 90
        base: "METTA"
      # Also allow an env variable containing json to be used as a dictionary of
      # config source.  There is some chance of collision with the previous plugin
      metta-env-json:
        plugin_id: env-json
        priority: 85
        env: METTA_CONFIGJSON

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
