
# Universal health poller for checking stability
healthpoller:
    plugin_id: healthpoll_workload

    from_config: true

    poll:
        # How often should we poll for health
        period: 10

# nginx-k8s-deployment :: metta.plugin.workload:
nginx-k8s-deployment:
    plugin_id: metta_kubernetes_deployment_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: "default"
    body:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.15.4
              ports:
              - containerPort: 80

metrics-helm-workload:
    plugin_id: metta_kubernetes_helm_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      bitnami: https://charts.bitnami.com/bitnami

    namespace: default
    chart: bitnami/metrics-server
    values:
      apiService:
        create: true
