
# Universal health poller for checking stability
healthpoller:
    plugin_id: healthpoll_workload

    from_config: true

    poll:
        # How often should we poll for health
        period: 10


# npods-support - supporting network and namespace for npods-workload
npods-workload:
    plugin_id: metta_kubernetes_helm_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    namespace: npods
    chart: "{{mirantis:helm.npods.chart.path}}"

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.npods.yaml"
    values:
      # Apply a mild workload of 400 pods with 150 relay threads
      workloads:
      - name: initial
        image: msr.ci.mirantis.com/jnesbitt/n-pods-app:0.18
        replicas: 350
        sleep: 100ms
        cpu: "10"
        ram: "128"
        threads: 200

# loki workload : monitoring tooling workload
loki-workload:
    plugin_id: metta_kubernetes_helm_workload

    # build the plugin from this config, by passing this label/base to it
    from_config: true

    repos:
      grafana: https://grafana.github.io/helm-charts

    namespace: loki
    chart: grafana/loki-stack

    file: "{{variables:files_path}}/{{variables:resource_prefix}}.helm.loki.yaml"
    values:

      loki:
        nodeSelector:
          com.docker.ucp.collection: system

      promtail:
        nodeSelector:
          com.docker.ucp.collection: system

      fluent-bit:
        nodeSelector:
          com.docker.ucp.collection: system

      grafana:
        enabled: true
        image:
          tag: 7.4.5

        adminUser: admin
        adminPassword: admin

        nodeSelector:
          com.docker.ucp.collection: system

        imageRenderer:
          enabled: true

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default

        dashboards:
          default:
            node-exporter-server-metrics:
              title: NodeExporter
              folder: general
              gnetId: 11952
              version: 1
              datasource: Prometheus
              refresh: 10s
              time:
                from: "now-30m"
                to: "now"

      prometheus:
        enabled: true

        nodeSelector:
          com.docker.ucp.collection: system

        alertmanager:
          persistentVolume:
            enabled: false
        server:
          persistentVolume:
            enabled: false
