
metrics-helm-workload:
    # @see https://github.com/james-nesbitt/metta/blob/main/mirantis/testing/metta_kubernetes/helm_workload.py
    plugin_type: workload
    plugin_id: metta_kubernetes_helm
    # build the plugin from this config, by passing this label/base to it
    from_config: true

    #----------------------------------
    # @see https://github.com/james-nesbitt/metta/blob/main/mirantis/testing/metta_kubernetes/helm_workload.py#L67
    repos:
      bitnami: https://charts.bitnami.com/bitnami

    namespace: default
    chart: bitnami/metrics-server
    values:
      apiService.create: true
