# In this file we define configuration used to create a Metta Environment.
#
# The environment object acts as a container for fixtures. The object itself
# will be created by the bootstrapper plugin which is defined in the root
# metta.yml file (it points here to define environments).
#
# Typically the bootstrapper creates this as a globally available fixture
# and the mirantis.testing.metta.get_environment() function can be used to
# retrieve it.
#
# The environment plugin we use is a BUILDER environment, which will use
# its own config to automatically build fixtures when it is created. The
# fixtures definition is below, but it typically redirects to a different
# fixtures.yml file.

# Create an environment called 'default'
default:
  # Environment plugin to use
  plugin_id: metta_state_environment

  # this tells metta that this config block should be passed to the plugin
  # for config use (you could tell it to load from a different source.)
  from_config: true

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
