
# Create an environment called '2021Q1'
2021Q1:
  bootstraps:
    metta:
    - metta_ansible
    - metta_docker
    - metta_dummy
    - metta_launchpad
    - metta_kubernetes
    - metta_terraform

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
