
# Create an environment called 'default'
default:
  bootstraps:
    metta:
    - metta_terraform

  fixtures:
    from_config:
      # Load the fixtures from fixtures(.yml) source.
      label: fixtures
