
# terraform :: metta.plugin.provisioner:
terraform:
    plugin_id: metta_terraform

    # Tell terraform to configure itself from the ./terraform.yml file
    # This is actually its default but this demonstrates that we have
    # the option of setting any config path desired, including that we
    # could embed the terraform.yml file here.
    from_config:
        label: terraform
        # base: some.path.in.the.terraform.file
