{{- range .Values.workloads }}
---
# Start relay threads using curl jobs
apiVersion: batch/v1
kind: Job
metadata:
  name: npod-trigger-{{ .name }}
  labels:
    app: npods-workload
    workload: npods-workload-{{ .name }}
spec:
  template:
    spec:
      containers:
      - name: trigger
        image: curlimages/curl
        command: ["bin/sh"]
        args:
        - "-c"
        - "for i in $(seq 1 {{ .threads }}); do curl -sL npods-relay-{{ .name }}?thread={{ .name }}-$i; echo; done"
      restartPolicy: Never
  completions: 1
{{- end -}}
